WIP - Jerk limits
DexaiRobotics/toppra pull request #6
Opened 2019-07-24 19:58 UTC by duncancmt-dexai

2019-07-24 19:59 UTC, duncancmt-dexai commented on toppra/dracula/three_segment_spline.py
> +        C_ret[i,::,0] /= scale**3
I couldn't wrap my head around the correct algebra for scaling the coefficients. I'll come back at this tomorrow

2019-07-26 16:02 UTC, duncancmt-dexai commented
This branch will be deleted on Friday, August 2nd because it will be superseded by other work

2019-07-29 12:26 UTC, tarquasso commented
@duncancmt-dexai How much work would it take to finish this PR?

2019-07-29 12:27 UTC, tarquasso commented
please leave this PR open until the solution from Gavin comes in.

2019-07-29 14:57 UTC, duncancmt-dexai commented
It shouldn't require much extra work to get this merged. I'll do that immediately

2019-07-30 14:38 UTC, tarquasso commented
is this ready for review?

2019-07-30 14:56 UTC, duncancmt-dexai commented
Ready for review, but still needs on-robot testing

2019-08-05 18:54 UTC, tarquasso commented
@duncancmt-dexai Please make two RunTopp calls: one with jerk limit at start and end, and one with jerk limits for all segments.

2019-08-05 18:55 UTC, tarquasso requested changes
Please make two RunTopp calls: old version that only fixes start and end, and this new version you are proposing here.

2019-08-05 18:55 UTC, tarquasso commented on toppra/dracula/topp_dracula_interface.py
> +def RunTopp(knots_ext, vlim, alim, jlim, robot_command_rate, return_spline_parameters = False, topp_breaks_count = 1001, debug_active = False):
create a seaprate RunTopp version for the jerk limitation on all segments

2019-08-05 18:55 UTC, tarquasso commented on toppra/dracula/topp_dracula_interface.py
> -    ZeroAccelerationAtStartAndEnd(jnt_traj.cspl)
keep this alive in one of the versions

2020-11-10 03:54 UTC, duanyutong commented
closing as this appears no longer needed

2020-11-10 03:54 UTC, closed without merging